### ISSUE TITLE
Provide an ability to configure `PS1`

### ISSUE THREAD

**Issue by adaszko** [assert-rs/completest#13]
To simplify tests using completest, I'd like to have an ability to set `PS1=""`.  Currently I'm forced to take into account the configured prompt (`% `) in my assertions.

**Comment by epage** [comment]
Could you help me understand how `PS1=""` would help?

Depending on the shell, the first line of output is a full prompt line which would have to be taken into account.

Customizing `PS1` also gets into shell-specific behaviors.

**Comment by adaszko** [comment]
> Could you help me understand how `PS1=""` would help?
> 
> Depending on the shell, the first line of output is a full prompt line which would have to be taken into account.
> 
> Customizing `PS1` also gets into shell-specific behaviors.

Sure thing.  Setting the prompt to an empty one would simplify my tests because I'm only interested in checking the completion output, not the prompt.  With an empty one, I can simply ignore the prompt.

The runtime constructors are already shell-specific, so that shouldn't be a problem, no?

**Comment by epage** [comment]
> Sure thing. Setting the prompt to an empty one would simplify my tests because I'm only interested in checking the completion output, not the prompt. With an empty one, I can simply ignore the prompt.

Take this zsh test from [`clap_complete`](https://github.com/clap-rs/clap/blob/master/clap_complete/tests/testsuite/zsh.rs#L131):
```rust
#[test]
#[cfg(unix)]
fn complete() {
    if !common::has_command("zsh") {
        return;
    }

    let term = completest::Term::new();
    let mut runtime = common::load_runtime("static", "exhaustive", completest::Shell::Zsh);

    let input = "exhaustive \t";
    let expected = r#"% exhaustive
complete                                           -- Register shell completions for this program
help                                               -- Print this message or the help of the given subcommand(s)
pacman    action  alias  value  quote  hint  last  --"#;
    let actual = runtime.complete(input, &term).unwrap();
    snapbox::assert_eq(expected, actual);
}
````
With `PS1=""`, the first line would change from `% exhaustive` to ` exhaustive`, meaning you still have the prompt line and not just completion output.

I am considering creating an equivalent of [trycmd](https://docs.rs/trycmd/latest/trycmd/) which would extract completion lines from `md` files and verify them.  I would expect it to strip the first line before comparing output.

**Comment by epage** [comment]
> The runtime constructors are already shell-specific, so that shouldn't be a problem, no?

Yes, and we can support per-shell features if needed.

Ideally people can more easily scale their tests than having to configure things per-shell.  For example, I pass around a `Shell` variant and perform operations on that instead, making my code more generic.  I would expect similar for my `trycomplete` idea

**Comment by epage** [comment]
> That's not what I'm seeing on zsh. After executing PS1="", I'm not seeing the initial space, so it's exhaustive, not  exhaustive:

The space wasn't my point but that you are still getting a prompt-line in the output which I thought you were trying to avoid, that you would get `exhaustive` or `exhaustive -` or whatever line it is that is being completed.

**Comment by adaszko** [comment]
> > That's not what I'm seeing on zsh. After executing PS1="", I'm not seeing the initial space, so it's exhaustive, not  exhaustive:
> 
> The space wasn't my point but that you are still getting a prompt-line in the output which I thought you were trying to avoid, that you would get `exhaustive` or `exhaustive -` or whatever line it is that is being completed.

That's fine.  The command is part of the thing I'm testing, so I'm good with it.  The prompt isn't.

**Comment by epage** [comment]
For me, I think if a prompt line is being shown at all, it should have a distinguishing mark to show that it is a prompt line.  If you want the prompt removed, I would recommend going the route of removing the entire first line.

**Comment by adaszko** [comment]
I'm doing open source so I'm supposed to be having fun and I'm not but I'll make one more attempt:

For this test case:
```Rust
    #[test]
    fn completest_reduction() {
        let script = r#"
#compdef foo

_foo () {
    compadd bar
    return 0
}
compdef _foo foo
"#;
        let term = completest::Term::new();
        let mut runtime = completest::ZshRuntime::new(PathBuf::from_str("/opt/homebrew/bin").unwrap(), PathBuf::from_str("./completest-temporary-directory").unwrap()).unwrap();
        runtime.register("foo", &script).unwrap();
        let output = runtime.complete("foo \t", &term).unwrap();
        dbg!(output);
    }
```

I'm getting this output:

```
running 1 test
[src/zsh.rs:406] output = "adaszko@pryk complgen % foo\nCONTRIBUTING.md                  examples/                        psql.usage\nCargo.lock                       foo/                             psql.zsh\nCargo.toml                       help.usage                       pytest.ini\nLICENSE                          help.zsh                         run-e2e-tests.bash*\nREADME.md                        lsof.bash                        src/\nassets/                          lsof.fish                        strace.fish\ncapture_postamble.zsh            lsof.zsh                         strace.usage\ncapture_preamble.zsh             my.bash                          strace.zsh\ncargo.fish                       my.fish                          target/\ncompletest-temporary-directory/  my.usage                         usage/\ndfa.dot                          my.zsh                           venv/\ndfa.svg                          pgservice.conf\ne2e/                             proptest-regressions/"
```

So the prompt setting at https://github.com/assert-rs/completest/blob/main/src/pty.rs#L32 doesn't seem to be doing its job.

**Comment by adaszko** [comment]
Take this example then:

```
    #[test]
    fn completest_reduction() {
        let script = r#"#compdef foo

_foo () {
    compadd -- --bar
    return 0
}
compdef _foo foo
"#;
        let term = completest::Term::new();
        let mut runtime = completest::ZshRuntime::new(PathBuf::from_str("/opt/homebrew/bin").unwrap(), PathBuf::from_str("./foo").unwrap()).unwrap();
        runtime.register("foo", &script).unwrap();
        let output = runtime.complete("foo \t\t", &term).unwrap();
        dbg!(output);
    }
```

The output is `[src/zsh.rs:405] output = "% foo --bar"` so the completion is in the same line as the prompt.  It doesn't make sense to strip the first line then.
