### ISSUE TITLE
Can’t get simple zsh completion to work

### ISSUE THREAD

**Issue by adaszko** [assert-rs/completest#6]
Hi 👋 

I’m on macOS, trying to write a simple test case.  This just outputs a bunch of files from the current directory, not `bar`, as it should have.  When I `source` the completion script from the shell, it works fine.

```Rust
    #[test]
    fn completest_reduction() {
        let script = r#"
#compdef foo

_foo () {
    compadd bar
    return 0
}
compdef _foo foo
"#;
        let term = completest::Term::new();
        let mut runtime = completest::ZshRuntime::new(PathBuf::from_str("/opt/homebrew/bin/zsh").unwrap(), PathBuf::from_str("./completest-temporary-directory").unwrap()).unwrap();
        runtime.register("foo", &script).unwrap();
        let output = runtime.complete("foo \t", &term).unwrap();
        dbg!(output);
    }
```

```
    Running unittests src/main.rs (target/debug/deps/complgen-fd528e5e370143a6)

running 1 test
[src/zsh.rs:404] output = "adaszko@pryk complgen % foo\nCONTRIBUTING.md                  e2e/                             psql.usage\nCargo.lock                       examples/                        psql.zsh\nCargo.toml                       help.usage                       pytest.ini\nLICENSE                          help.zsh                         run-e2e-tests.bash*\nREADME.md                        lsof.bash                        src/\nassets/                          lsof.zsh                         strace.fish\ncapture_postamble.zsh            my.bash                          strace.usage\ncapture_preamble.zsh             my.fish                          strace.zsh\ncargo.fish                       my.usage                         target/\ncompletest-temporary-directory/  my.zsh                           usage/\ndfa.dot                          pgservice.conf                   venv/\ndfa.svg                          proptest-regressions/"
test zsh::tests::completest_reduction ... ok
```

**Comment by epage** [comment]
> BTW, I also accidentally overwrote my .zshenv because I set the ZshRuntime::new()’s [home](https://docs.rs/completest/latest/completest/struct.ZshRuntime.html#method.new) parameter to my actual home directory. Had to restore it from backups. That may be something worth documenting as well ;) Or better yet, use a mktemp directory by default.

Mind creating an issue on how we can clarify this?

Since we are writing directly to the directory and there are users today not using a temp directory (clap), we need to make sure this is handled in the right way.

> That didn’t work either. What fixed it was the addition of rm $ZDOTDIR/.zcompdump at the beginning of completest-temporary-directory/.zshenv.

*shrug* no idea.  I guess we could always delete that file when initializing to reduce the chance of bugs

I think I had missed that because I copy I do a lot of filesystem shenanigans

**Comment by adaszko** [comment]
Created #9 :)
